export type DocEntry = { slug: string; title: string; description: string; source: string; parent?: string };
export type DocGroup = { label: string; docs: DocEntry[] };

export const docGroups: DocGroup[] = [
  { label: "Start here", docs: [
    { slug: "engine", title: "Using Rustic Engine", description: "Create a game, attach scripts, and learn how to use the editor and gameplay API.", source: "content/engine.md" },
    { slug: "api/overview", title: "API overview", description: "Rustic API concepts, language support, and execution rules.", source: "api:overview" },
    { slug: "callbacks", title: "Lifecycle callbacks", description: "Choose the correct callback for setup, frames, physics, and teardown.", source: "api:callbacks" },
  ] },
  { label: "Core API", docs: [
    { slug: "api/entity", title: "Entity & time", description: "Read the current entity ID and frame timing.", source: "content/entity-and-time.md" },
    { slug: "api/entity/identity", title: "Entity identity", description: "Read the behavior owner’s stable entity ID.", source: "api:entity-identity", parent: "api/entity" },
    { slug: "api/entity/frame-time", title: "Frame time", description: "Read frame and fixed-step intervals in seconds.", source: "api:frame-time", parent: "api/entity" },
    { slug: "api/transforms", title: "Transforms", description: "Read and change the owning entity's position.", source: "api:transforms" },
    { slug: "api/properties", title: "Public properties", description: "Read and update declared script properties.", source: "api:properties" },
    { slug: "api/attributes", title: "Built-in attributes", description: "Read or edit engine-owned entity attributes.", source: "api:attributes" },
    { slug: "api/input", title: "Input", description: "Use held keys in Play and see current input limits.", source: "api:input" },
    { slug: "api/logging", title: "Logging", description: "Write bounded messages to the live game console.", source: "api:logging" },
    { slug: "api/enabled", title: "Enabled state", description: "Enable or disable the owning behavior entity.", source: "api:enabled" },
  ] },
  { label: "Gameplay APIs", docs: [
    { slug: "api/gameplay", title: "Gameplay actions", description: "Find the focused reference for each gameplay module.", source: "content/gameplay-api.md" },
    { slug: "guides/gameplay-actions", title: "Use gameplay actions", description: "Choose a focused guide to use gameplay actions.", source: "docs/Scripting/gameplayActions.md" },
    { slug: "guides/gameplay-actions/setup", title: "Set up gameplay actions", description: "Set up gameplay actions for Use gameplay actions.", source: "docs/Scripting/gameplayActions/setup.md", parent: "guides/gameplay-actions" },
    { slug: "guides/gameplay-actions/language-bindings", title: "Gameplay language bindings", description: "Gameplay language bindings for Use gameplay actions.", source: "docs/Scripting/gameplayActions/language-bindings.md", parent: "guides/gameplay-actions" },
    { slug: "guides/gameplay-actions/easing", title: "Choose easing curves", description: "Choose easing curves for Use gameplay actions.", source: "docs/Scripting/gameplayActions/easing.md", parent: "guides/gameplay-actions" },
    { slug: "guides/gameplay-actions/timing", title: "Set action duration or speed", description: "Set action duration or speed for Use gameplay actions.", source: "docs/Scripting/gameplayActions/timing.md", parent: "guides/gameplay-actions" },
    { slug: "guides/gameplay-actions/properties", title: "Animate entity properties", description: "Animate entity properties for Use gameplay actions.", source: "docs/Scripting/gameplayActions/properties.md", parent: "guides/gameplay-actions" },
    { slug: "guides/gameplay-actions/value-tweens", title: "Tween script values", description: "Tween script values for Use gameplay actions.", source: "docs/Scripting/gameplayActions/value-tweens.md", parent: "guides/gameplay-actions" },
    { slug: "guides/gameplay-actions/paths", title: "Follow a path", description: "Follow a path for Use gameplay actions.", source: "docs/Scripting/gameplayActions/paths.md", parent: "guides/gameplay-actions" },
    { slug: "guides/gameplay-actions/timers", title: "Schedule timers", description: "Schedule timers for Use gameplay actions.", source: "docs/Scripting/gameplayActions/timers.md", parent: "guides/gameplay-actions" },
    { slug: "guides/gameplay-actions/operation-handles", title: "Control operation handles", description: "Control operation handles for Use gameplay actions.", source: "docs/Scripting/gameplayActions/operation-handles.md", parent: "guides/gameplay-actions" },
    { slug: "guides/gameplay-actions/sequences", title: "Compose sequences", description: "Compose sequences for Use gameplay actions.", source: "docs/Scripting/gameplayActions/sequences.md", parent: "guides/gameplay-actions" },
    { slug: "guides/gameplay-actions/camera", title: "Animate a camera", description: "Animate a camera for Use gameplay actions.", source: "docs/Scripting/gameplayActions/camera.md", parent: "guides/gameplay-actions" },
    { slug: "guides/gameplay-actions/movement", title: "Follow and orbit objects", description: "Follow and orbit objects for Use gameplay actions.", source: "docs/Scripting/gameplayActions/movement.md", parent: "guides/gameplay-actions" },
    { slug: "guides/gameplay-actions/effects", title: "Apply visual effects", description: "Apply visual effects for Use gameplay actions.", source: "docs/Scripting/gameplayActions/effects.md", parent: "guides/gameplay-actions" },
    { slug: "guides/gameplay-actions/events", title: "Send events and object signals", description: "Send events and object signals for Use gameplay actions.", source: "docs/Scripting/gameplayActions/events.md", parent: "guides/gameplay-actions" },
    { slug: "guides/gameplay-actions/clock", title: "Control the scene clock", description: "Control the scene clock for Use gameplay actions.", source: "docs/Scripting/gameplayActions/clock.md", parent: "guides/gameplay-actions" },
    { slug: "guides/gameplay-actions/lifetime", title: "Understand action cleanup", description: "Understand action cleanup for Use gameplay actions.", source: "docs/Scripting/gameplayActions/lifetime.md", parent: "guides/gameplay-actions" },
    { slug: "guides/gameplay-actions/diagnosis", title: "Diagnose gameplay actions", description: "Diagnose gameplay actions for Use gameplay actions.", source: "docs/Scripting/gameplayActions/diagnosis.md", parent: "guides/gameplay-actions" },
    { slug: "guides/gameplay-actions/imported-animation", title: "Play imported animation clips", description: "Play imported animation clips for Use gameplay actions.", source: "docs/Scripting/gameplayActions/imported-animation.md", parent: "guides/gameplay-actions" },
    { slug: "guides/gameplay-actions/animation-layers", title: "Layer animation clips", description: "Layer animation clips for Use gameplay actions.", source: "docs/Scripting/gameplayActions/animation-layers.md", parent: "guides/gameplay-actions" },
    { slug: "guides/gameplay-actions/animation-tracks", title: "Register animation tracks", description: "Register animation tracks for Use gameplay actions.", source: "docs/Scripting/gameplayActions/animation-tracks.md", parent: "guides/gameplay-actions" },
    { slug: "guides/gameplay-actions/value-keyframes", title: "Animate script value keyframes", description: "Animate script value keyframes for Use gameplay actions.", source: "docs/Scripting/gameplayActions/value-keyframes.md", parent: "guides/gameplay-actions" },
    { slug: "guides/gameplay-actions/procedural-animation", title: "Use procedural animation", description: "Use procedural animation for Use gameplay actions.", source: "docs/Scripting/gameplayActions/procedural-animation.md", parent: "guides/gameplay-actions" },
    { slug: "guides/gameplay-actions/interpolation", title: "Evaluate interpolation", description: "Evaluate interpolation for Use gameplay actions.", source: "docs/Scripting/gameplayActions/interpolation.md", parent: "guides/gameplay-actions" },
    { slug: "guides/gameplay-actions/physics-queries", title: "Query physics colliders", description: "Query physics colliders for Use gameplay actions.", source: "docs/Scripting/gameplayActions/physics-queries.md", parent: "guides/gameplay-actions" },
    { slug: "guides/gameplay-actions/physics-forces", title: "Apply physics forces", description: "Apply physics forces for Use gameplay actions.", source: "docs/Scripting/gameplayActions/physics-forces.md", parent: "guides/gameplay-actions" },
    { slug: "guides/gameplay-actions/audio", title: "Play and fade audio", description: "Play and fade audio for Use gameplay actions.", source: "docs/Scripting/gameplayActions/audio.md", parent: "guides/gameplay-actions" },
    { slug: "guides/gameplay-actions/validation", title: "Validate gameplay services", description: "Validate gameplay services for Use gameplay actions.", source: "docs/Scripting/gameplayActions/validation.md", parent: "guides/gameplay-actions" },
    { slug: "guides/gameplay-actions/extension", title: "Extend gameplay services", description: "Extend gameplay services for Use gameplay actions.", source: "docs/Scripting/gameplayActions/extension.md", parent: "guides/gameplay-actions" },
    { slug: "guides/gameplay-architecture", title: "Gameplay API architecture", description: "Core services, property adapters, clip handles, timing and lifetime boundaries.", source: "docs/GAMEPLAY_API_ARCHITECTURE.md" },
    { slug: "api/tween", title: "Tween", description: "Animate an entity property or script value without writing an Update loop.", source: "docs/Scripting/API/tween.md" },
    { slug: "api/ease", title: "Ease", description: "Choose one of 31 shared easing curves for actions and synchronous interpolation.", source: "docs/Scripting/API/ease.md" },
    { slug: "api/movement", title: "Movement", description: "Move, turn, follow and orbit objects with finite engine-scheduled actions.", source: "docs/Scripting/API/movement.md" },
    { slug: "api/animation", title: "Animation", description: "Play imported skeletal clips, register property tracks, animate script values and run procedural poses.", source: "docs/Scripting/API/animation.md" },
    { slug: "api/sequence", title: "Sequence and Timeline", description: "Compose sequential and parallel actions without nesting timer callbacks.", source: "docs/Scripting/API/sequence.md" },
    { slug: "api/timer", title: "Timer", description: "Schedule one-shot or repeating scene-clock callbacks.", source: "docs/Scripting/API/timer.md" },
    { slug: "api/smooth", title: "Smooth and Interpolation", description: "Evaluate interpolation and damping immediately without scheduling an action.", source: "docs/Scripting/API/smooth.md" },
    { slug: "api/path", title: "Path", description: "Traverse linear, Bezier and spline paths with global and per-segment easing.", source: "docs/Scripting/API/path.md" },
    { slug: "api/camera-actions", title: "Camera actions", description: "Move, aim, zoom, follow and shake a game camera using shared actions.", source: "docs/Scripting/API/camera-actions.md" },
    { slug: "api/physics-actions", title: "Physics queries and forces", description: "Query live primitive colliders and change simulated body velocity.", source: "docs/Scripting/API/physics-actions.md" },
    { slug: "api/physics-actions/queries", title: "Physics queries", description: "Find primitive colliders with raycasts, sphere casts and overlaps.", source: "docs/Scripting/API/physics-actions/queries.md", parent: "api/physics-actions" },
    { slug: "api/physics-actions/forces", title: "Physics forces", description: "Apply forces, impulses and velocity changes to simulated bodies.", source: "docs/Scripting/API/physics-actions/forces.md", parent: "api/physics-actions" },
    { slug: "api/effects", title: "Effects", description: "Fade, flash, shake and pulse entity properties with shared easing.", source: "docs/Scripting/API/effects.md" },
    { slug: "api/audio", title: "Audio", description: "Play engine-decoded WAV/OGG voices, adjust parameters and schedule fades.", source: "docs/Scripting/API/audio.md" },
    { slug: "api/events", title: "Events and signals", description: "Communicate through queued global events and object-scoped signals across scripting languages.", source: "docs/Scripting/API/events.md" },
    { slug: "api/clock", title: "Clock", description: "Scale or pause the shared scene clock for actions, animation, physics and audio.", source: "docs/Scripting/API/clock.md" },
    { slug: "api/operation-handles", title: "Operation handles", description: "Inspect, pause, resume, cancel and observe engine-scheduled actions.", source: "docs/Scripting/API/operation-handles.md" },
  ] },
  { label: "Scene API", docs: [
    { slug: "guides/scene-objects", title: "Edit scene objects", description: "Target an object by scene name and hierarchy in any script language.", source: "docs/Scripting/sceneObjects.md" },
    { slug: "api/environment", title: "Scene environment", description: "Read and change sky textures, ambient and sun lighting, and haze from every script language.", source: "api:environment" },
    { slug: "api/scene", title: "Scene lookup", description: "Find entities and enumerate stable scene paths.", source: "api:scene" },
    { slug: "api/instances", title: "Add & clone instances", description: "Queue creation from a source path with an optional parent.", source: "api:instances" },
    { slug: "api/camera", title: "Current camera", description: "Select the active game camera by path or entity ID.", source: "api:camera" },
  ] },
  { label: "Engine guides", docs: [
    { slug: "guides/scene-environment", title: "Sky & atmosphere", description: "Choose a focused guide to sky & atmosphere.", source: "docs/SCENE_ENVIRONMENT.md" },
    { slug: "guides/scene-environment/script-diagnosis", title: "Diagnose environment script changes", description: "Diagnose environment script changes.", source: "docs/SCENE_ENVIRONMENT/script-diagnosis.md", parent: "guides/scene-environment" },
    { slug: "guides/scene-environment/language-calls", title: "Environment calls in other languages", description: "Environment calls in other languages.", source: "docs/SCENE_ENVIRONMENT/language-calls.md", parent: "guides/scene-environment" },
    { slug: "guides/scene-environment/scripting", title: "Change the environment from scripts", description: "Change the environment from scripts.", source: "docs/SCENE_ENVIRONMENT/scripting.md", parent: "guides/scene-environment" },
    { slug: "guides/scene-environment/set-up-a-sky", title: "Set up a sky", description: "Set up a sky for Sky & atmosphere.", source: "docs/SCENE_ENVIRONMENT/set-up-a-sky.md", parent: "guides/scene-environment" },
    { slug: "guides/scene-environment/lighting-and-haze", title: "Lighting and haze", description: "Lighting and haze for Sky & atmosphere.", source: "docs/SCENE_ENVIRONMENT/lighting-and-haze.md", parent: "guides/scene-environment" },
    { slug: "guides/scene-environment/diagnose-problems", title: "Diagnose problems", description: "Diagnose problems for Sky & atmosphere.", source: "docs/SCENE_ENVIRONMENT/diagnose-problems.md", parent: "guides/scene-environment" },
    { slug: "guides/physics", title: "Basic physics", description: "Gravity, falling primitives, collision, anchored floors, and current limits.", source: "docs/PHYSICS.md" },
    { slug: "guides/ai-agents", title: "AI agents & app data", description: "Choose a focused guide to ai agents & app data.", source: "docs/AGENT_INTEGRATION.md" },
    { slug: "guides/ai-agents/connect-an-agent", title: "Connect an agent", description: "Connect an agent for AI agents & app data.", source: "docs/AGENT_INTEGRATION/connect-an-agent.md", parent: "guides/ai-agents" },
    { slug: "guides/ai-agents/read-and-edit-agent-information", title: "Read and edit agent information", description: "Read and edit agent information for AI agents & app data.", source: "docs/AGENT_INTEGRATION/read-and-edit-agent-information.md", parent: "guides/ai-agents" },
    { slug: "guides/ai-agents/storage-and-migration", title: "Storage and migration", description: "Storage and migration for AI agents & app data.", source: "docs/AGENT_INTEGRATION/storage-and-migration.md", parent: "guides/ai-agents" },
    { slug: "guides/ai-agents/limits-and-troubleshooting", title: "Limits and troubleshooting", description: "Limits and troubleshooting for AI agents & app data.", source: "docs/AGENT_INTEGRATION/limits-and-troubleshooting.md", parent: "guides/ai-agents" },
    { slug: "guides/gameplay-programming", title: "Gameplay programming", description: "Choose a focused guide to gameplay programming.", source: "docs/GAMEPLAY_PROGRAMMING.md" },
    { slug: "guides/gameplay-programming/project-layout-and-ownership", title: "Project layout and ownership", description: "Project layout and ownership for Gameplay programming.", source: "docs/GAMEPLAY_PROGRAMMING/project-layout-and-ownership.md", parent: "guides/gameplay-programming" },
    { slug: "guides/gameplay-programming/lifecycle-execution-order-and-api-1-0", title: "Lifecycle, execution order, and API 1.0", description: "Lifecycle, execution order, and API 1.0 for Gameplay programming.", source: "docs/GAMEPLAY_PROGRAMMING/lifecycle-execution-order-and-api-1-0.md", parent: "guides/gameplay-programming" },
    { slug: "guides/gameplay-programming/javascript-lifecycle-and-api-1-0", title: "JavaScript lifecycle and API 1.0", description: "JavaScript lifecycle and API 1.0 for Gameplay programming.", source: "docs/GAMEPLAY_PROGRAMMING/javascript-lifecycle-and-api-1-0.md", parent: "guides/gameplay-programming" },
    { slug: "guides/gameplay-programming/external-process-languages", title: "External process languages", description: "External process languages for Gameplay programming.", source: "docs/GAMEPLAY_PROGRAMMING/external-process-languages.md", parent: "guides/gameplay-programming" },
    { slug: "guides/gameplay-programming/external-process-languages/selecting-the-game-camera", title: "Selecting the game camera", description: "Selecting the game camera for External process languages.", source: "docs/GAMEPLAY_PROGRAMMING/external-process-languages/selecting-the-game-camera.md", parent: "guides/gameplay-programming/external-process-languages" },
    { slug: "guides/gameplay-programming/external-process-languages/runtime-integration", title: "External language runtime integration", description: "External language runtime integration for External process languages.", source: "docs/GAMEPLAY_PROGRAMMING/external-process-languages/runtime-integration.md", parent: "guides/gameplay-programming/external-process-languages" },
    { slug: "guides/gameplay-programming/external-process-languages/native-callback-setup", title: "Native callback setup", description: "Native callback setup for External process languages.", source: "docs/GAMEPLAY_PROGRAMMING/external-process-languages/native-callback-setup.md", parent: "guides/gameplay-programming/external-process-languages" },
    { slug: "guides/gameplay-programming/external-process-languages/c-api", title: "C++ API", description: "C++ API for External process languages.", source: "docs/GAMEPLAY_PROGRAMMING/external-process-languages/c-api.md", parent: "guides/gameplay-programming/external-process-languages" },
    { slug: "guides/gameplay-programming/external-process-languages/toolchains", title: "Install external language toolchains", description: "Install external language toolchains for External process languages.", source: "docs/GAMEPLAY_PROGRAMMING/external-process-languages/toolchains.md", parent: "guides/gameplay-programming/external-process-languages" },
    { slug: "guides/gameplay-programming/html-css-content", title: "HTML/CSS content", description: "HTML/CSS content for Gameplay programming.", source: "docs/GAMEPLAY_PROGRAMMING/html-css-content.md", parent: "guides/gameplay-programming" },
    { slug: "guides/gameplay-programming/validation-diagnostics-and-reload", title: "Validation, diagnostics, and reload", description: "Validation, diagnostics, and reload for Gameplay programming.", source: "docs/GAMEPLAY_PROGRAMMING/validation-diagnostics-and-reload.md", parent: "guides/gameplay-programming" },
    { slug: "guides/gameplay-programming/sandbox-and-play-safety", title: "Sandbox and play safety", description: "Sandbox and play safety for Gameplay programming.", source: "docs/GAMEPLAY_PROGRAMMING/sandbox-and-play-safety.md", parent: "guides/gameplay-programming" },
    { slug: "guides/gameplay-programming/troubleshooting", title: "Troubleshooting", description: "Troubleshooting for Gameplay programming.", source: "docs/GAMEPLAY_PROGRAMMING/troubleshooting.md", parent: "guides/gameplay-programming" },
    { slug: "guides/cameras-and-lights", title: "Cameras & lights", description: "Choose a focused guide to cameras & lights.", source: "docs/CAMERAS_AND_LIGHTS.md" },
    { slug: "guides/cameras-and-lights/camera", title: "Camera", description: "Camera for Cameras & lights.", source: "docs/CAMERAS_AND_LIGHTS/camera.md", parent: "guides/cameras-and-lights" },
    { slug: "guides/cameras-and-lights/light", title: "Light", description: "Light for Cameras & lights.", source: "docs/CAMERAS_AND_LIGHTS/light.md", parent: "guides/cameras-and-lights" },
    { slug: "guides/cameras-and-lights/move-and-scale-handles", title: "Move and scale handles", description: "Move and scale handles for Cameras & lights.", source: "docs/CAMERAS_AND_LIGHTS/move-and-scale-handles.md", parent: "guides/cameras-and-lights" },
    { slug: "guides/cameras-and-lights/scene-selection-outline", title: "Scene selection outline", description: "Scene selection outline for Cameras & lights.", source: "docs/CAMERAS_AND_LIGHTS/scene-selection-outline.md", parent: "guides/cameras-and-lights" },
    { slug: "guides/cameras-and-lights/verification", title: "Verification", description: "Verification for Cameras & lights.", source: "docs/CAMERAS_AND_LIGHTS/verification.md", parent: "guides/cameras-and-lights" },
  ] },
  { label: "Scripting languages", docs: [
    { slug: "scripting/lua", title: "Lua 5.4", description: "Choose a focused guide to lua 5.4.", source: "docs/Scripting/scriptingLua.md" },
    { slug: "scripting/lua/attach-and-choose-a-scope", title: "Attach and choose a scope", description: "Attach and choose a scope for Lua 5.4.", source: "docs/Scripting/scriptingLua/attach-and-choose-a-scope.md", parent: "scripting/lua" },
    { slug: "scripting/lua/module-and-callbacks", title: "Module and callbacks", description: "Module and callbacks for Lua 5.4.", source: "docs/Scripting/scriptingLua/module-and-callbacks.md", parent: "scripting/lua" },
    { slug: "scripting/lua/script-api", title: "Script API", description: "Script API for Lua 5.4.", source: "docs/Scripting/scriptingLua/script-api.md", parent: "scripting/lua" },
    { slug: "scripting/lua/finding-and-creating-objects", title: "Finding and creating objects", description: "Finding and creating objects for Lua 5.4.", source: "docs/Scripting/scriptingLua/finding-and-creating-objects.md", parent: "scripting/lua" },
    { slug: "scripting/lua/input", title: "Input", description: "Input for Lua 5.4.", source: "docs/Scripting/scriptingLua/input.md", parent: "scripting/lua" },
    { slug: "scripting/lua/isolation-and-failures", title: "Isolation and failures", description: "Isolation and failures for Lua 5.4.", source: "docs/Scripting/scriptingLua/isolation-and-failures.md", parent: "scripting/lua" },
    { slug: "scripting/javascript", title: "JavaScript", description: "Choose a focused guide to javascript.", source: "docs/Scripting/scriptingJavaScript.md" },
    { slug: "scripting/javascript/behavior-lifecycle", title: "Behavior lifecycle", description: "Behavior lifecycle for JavaScript.", source: "docs/Scripting/scriptingJavaScript/behavior-lifecycle.md", parent: "scripting/javascript" },
    { slug: "scripting/javascript/api-reference", title: "API reference", description: "API reference for JavaScript.", source: "docs/Scripting/scriptingJavaScript/api-reference.md", parent: "scripting/javascript" },
    { slug: "scripting/javascript/scene-instances-cameras-and-input", title: "Scene, instances, cameras, and input", description: "Scene, instances, cameras, and input for JavaScript.", source: "docs/Scripting/scriptingJavaScript/scene-instances-cameras-and-input.md", parent: "scripting/javascript" },
    { slug: "scripting/javascript/scene-instances-cameras-and-input/scene-lookup", title: "JavaScript scene lookup", description: "JavaScript scene lookup for Scene, instances, cameras, and input.", source: "docs/Scripting/scriptingJavaScript/scene-instances-cameras-and-input/scene-lookup.md", parent: "scripting/javascript/scene-instances-cameras-and-input" },
    { slug: "scripting/javascript/scene-instances-cameras-and-input/instances", title: "JavaScript instance creation", description: "JavaScript instance creation for Scene, instances, cameras, and input.", source: "docs/Scripting/scriptingJavaScript/scene-instances-cameras-and-input/instances.md", parent: "scripting/javascript/scene-instances-cameras-and-input" },
    { slug: "scripting/javascript/scene-instances-cameras-and-input/camera", title: "Select the JavaScript game camera", description: "Select the JavaScript game camera for Scene, instances, cameras, and input.", source: "docs/Scripting/scriptingJavaScript/scene-instances-cameras-and-input/camera.md", parent: "scripting/javascript/scene-instances-cameras-and-input" },
    { slug: "scripting/javascript/scene-instances-cameras-and-input/input", title: "JavaScript keyboard input", description: "JavaScript keyboard input for Scene, instances, cameras, and input.", source: "docs/Scripting/scriptingJavaScript/scene-instances-cameras-and-input/input.md", parent: "scripting/javascript/scene-instances-cameras-and-input" },
    { slug: "scripting/javascript/sandbox-values-and-diagnostics", title: "Sandbox, values, and diagnostics", description: "Sandbox, values, and diagnostics for JavaScript.", source: "docs/Scripting/scriptingJavaScript/sandbox-values-and-diagnostics.md", parent: "scripting/javascript" },
    { slug: "scripting/luau", title: "Luau", description: "Choose a focused guide to luau.", source: "docs/Scripting/scriptingLuau.md" },
    { slug: "scripting/luau/setup-and-attachment", title: "Setup and attachment", description: "Setup and attachment for Luau.", source: "docs/Scripting/scriptingLuau/setup-and-attachment.md", parent: "scripting/luau" },
    { slug: "scripting/luau/complete-behavior", title: "Complete behavior", description: "Complete behavior for Luau.", source: "docs/Scripting/scriptingLuau/complete-behavior.md", parent: "scripting/luau" },
    { slug: "scripting/luau/built-in-functions", title: "Built-in functions", description: "Built-in functions for Luau.", source: "docs/Scripting/scriptingLuau/built-in-functions.md", parent: "scripting/luau" },
    { slug: "scripting/luau/callbacks-and-values", title: "Callbacks and values", description: "Callbacks and values for Luau.", source: "docs/Scripting/scriptingLuau/callbacks-and-values.md", parent: "scripting/luau" },
    { slug: "scripting/luau/current-limits-and-diagnosis", title: "Current limits and diagnosis", description: "Current limits and diagnosis for Luau.", source: "docs/Scripting/scriptingLuau/current-limits-and-diagnosis.md", parent: "scripting/luau" },
    { slug: "scripting/python", title: "Python", description: "Choose a focused guide to python.", source: "docs/Scripting/scriptingPython.md" },
    { slug: "scripting/python/setup-and-attachment", title: "Setup and attachment", description: "Setup and attachment for Python.", source: "docs/Scripting/scriptingPython/setup-and-attachment.md", parent: "scripting/python" },
    { slug: "scripting/python/complete-behavior", title: "Complete behavior", description: "Complete behavior for Python.", source: "docs/Scripting/scriptingPython/complete-behavior.md", parent: "scripting/python" },
    { slug: "scripting/python/built-in-functions", title: "Built-in functions", description: "Built-in functions for Python.", source: "docs/Scripting/scriptingPython/built-in-functions.md", parent: "scripting/python" },
    { slug: "scripting/python/callbacks-and-values", title: "Callbacks and values", description: "Callbacks and values for Python.", source: "docs/Scripting/scriptingPython/callbacks-and-values.md", parent: "scripting/python" },
    { slug: "scripting/python/current-limits-and-diagnosis", title: "Current limits and diagnosis", description: "Current limits and diagnosis for Python.", source: "docs/Scripting/scriptingPython/current-limits-and-diagnosis.md", parent: "scripting/python" },
    { slug: "scripting/c", title: "C", description: "Choose a focused guide to c.", source: "docs/Scripting/scriptingC.md" },
    { slug: "scripting/c/setup-and-attachment", title: "Setup and attachment", description: "Setup and attachment for C.", source: "docs/Scripting/scriptingC/setup-and-attachment.md", parent: "scripting/c" },
    { slug: "scripting/c/complete-behavior", title: "Complete behavior", description: "Complete behavior for C.", source: "docs/Scripting/scriptingC/complete-behavior.md", parent: "scripting/c" },
    { slug: "scripting/c/built-in-functions", title: "Built-in functions", description: "Built-in functions for C.", source: "docs/Scripting/scriptingC/built-in-functions.md", parent: "scripting/c" },
    { slug: "scripting/c/callbacks-and-values", title: "Callbacks and values", description: "Callbacks and values for C.", source: "docs/Scripting/scriptingC/callbacks-and-values.md", parent: "scripting/c" },
    { slug: "scripting/c/current-limits-and-diagnosis", title: "Current limits and diagnosis", description: "Current limits and diagnosis for C.", source: "docs/Scripting/scriptingC/current-limits-and-diagnosis.md", parent: "scripting/c" },
    { slug: "scripting/cpp", title: "C++", description: "Choose a focused guide to c++.", source: "docs/Scripting/scriptingCpp.md" },
    { slug: "scripting/cpp/complete-behavior", title: "Complete behavior", description: "Complete behavior for C++.", source: "docs/Scripting/scriptingCpp/complete-behavior.md", parent: "scripting/cpp" },
    { slug: "scripting/cpp/typed-api", title: "Typed API", description: "Typed API for C++.", source: "docs/Scripting/scriptingCpp/typed-api.md", parent: "scripting/cpp" },
    { slug: "scripting/cpp/scene-and-object-operations", title: "Scene and object operations", description: "Scene and object operations for C++.", source: "docs/Scripting/scriptingCpp/scene-and-object-operations.md", parent: "scripting/cpp" },
    { slug: "scripting/cpp/lifetime-safety-and-compatibility", title: "Lifetime, safety, and compatibility", description: "Lifetime, safety, and compatibility for C++.", source: "docs/Scripting/scriptingCpp/lifetime-safety-and-compatibility.md", parent: "scripting/cpp" },
    { slug: "scripting/csharp", title: "C#", description: "Choose a focused guide to c#.", source: "docs/Scripting/scriptingCSharp.md" },
    { slug: "scripting/csharp/setup-and-attachment", title: "Setup and attachment", description: "Setup and attachment for C#.", source: "docs/Scripting/scriptingCSharp/setup-and-attachment.md", parent: "scripting/csharp" },
    { slug: "scripting/csharp/complete-behavior", title: "Complete behavior", description: "Complete behavior for C#.", source: "docs/Scripting/scriptingCSharp/complete-behavior.md", parent: "scripting/csharp" },
    { slug: "scripting/csharp/built-in-functions", title: "Built-in functions", description: "Built-in functions for C#.", source: "docs/Scripting/scriptingCSharp/built-in-functions.md", parent: "scripting/csharp" },
    { slug: "scripting/csharp/callbacks-and-values", title: "Callbacks and values", description: "Callbacks and values for C#.", source: "docs/Scripting/scriptingCSharp/callbacks-and-values.md", parent: "scripting/csharp" },
    { slug: "scripting/csharp/current-limits-and-diagnosis", title: "Current limits and diagnosis", description: "Current limits and diagnosis for C#.", source: "docs/Scripting/scriptingCSharp/current-limits-and-diagnosis.md", parent: "scripting/csharp" },
    { slug: "scripting/java", title: "Java", description: "Choose a focused guide to java.", source: "docs/Scripting/scriptingJava.md" },
    { slug: "scripting/java/setup-and-attachment", title: "Setup and attachment", description: "Setup and attachment for Java.", source: "docs/Scripting/scriptingJava/setup-and-attachment.md", parent: "scripting/java" },
    { slug: "scripting/java/complete-behavior", title: "Complete behavior", description: "Complete behavior for Java.", source: "docs/Scripting/scriptingJava/complete-behavior.md", parent: "scripting/java" },
    { slug: "scripting/java/built-in-functions", title: "Built-in functions", description: "Built-in functions for Java.", source: "docs/Scripting/scriptingJava/built-in-functions.md", parent: "scripting/java" },
    { slug: "scripting/java/callbacks-and-values", title: "Callbacks and values", description: "Callbacks and values for Java.", source: "docs/Scripting/scriptingJava/callbacks-and-values.md", parent: "scripting/java" },
    { slug: "scripting/java/current-limits-and-diagnosis", title: "Current limits and diagnosis", description: "Current limits and diagnosis for Java.", source: "docs/Scripting/scriptingJava/current-limits-and-diagnosis.md", parent: "scripting/java" },
    { slug: "scripting/php", title: "PHP", description: "Choose a focused guide to php.", source: "docs/Scripting/scriptingPHP.md" },
    { slug: "scripting/php/setup-and-attachment", title: "Setup and attachment", description: "Setup and attachment for PHP.", source: "docs/Scripting/scriptingPHP/setup-and-attachment.md", parent: "scripting/php" },
    { slug: "scripting/php/complete-behavior", title: "Complete behavior", description: "Complete behavior for PHP.", source: "docs/Scripting/scriptingPHP/complete-behavior.md", parent: "scripting/php" },
    { slug: "scripting/php/built-in-functions", title: "Built-in functions", description: "Built-in functions for PHP.", source: "docs/Scripting/scriptingPHP/built-in-functions.md", parent: "scripting/php" },
    { slug: "scripting/php/callbacks-and-values", title: "Callbacks and values", description: "Callbacks and values for PHP.", source: "docs/Scripting/scriptingPHP/callbacks-and-values.md", parent: "scripting/php" },
    { slug: "scripting/php/current-limits-and-diagnosis", title: "Current limits and diagnosis", description: "Current limits and diagnosis for PHP.", source: "docs/Scripting/scriptingPHP/current-limits-and-diagnosis.md", parent: "scripting/php" },
    { slug: "scripting/web", title: "HTML/CSS", description: "Choose a focused guide to html/css.", source: "docs/Scripting/scriptingWeb.md" },
    { slug: "scripting/web/html-behavior", title: "HTML behavior", description: "HTML behavior for HTML/CSS.", source: "docs/Scripting/scriptingWeb/html-behavior.md", parent: "scripting/web" },
    { slug: "scripting/web/available-inline-javascript-api", title: "Available inline JavaScript API", description: "Available inline JavaScript API for HTML/CSS.", source: "docs/Scripting/scriptingWeb/available-inline-javascript-api.md", parent: "scripting/web" },
    { slug: "scripting/web/security-and-limitations", title: "Security and limitations", description: "Security and limitations for HTML/CSS.", source: "docs/Scripting/scriptingWeb/security-and-limitations.md", parent: "scripting/web" },
  ] },
  { label: "Open-Sourced Docs", docs: [
    { slug: "open-source", title: "Open-Sourced Docs", description: "Repository development guides for the engine, docs, examples, and hosting SDK.", source: "content/repositories.md" },
  ] },
  { label: "Engine source", docs: [
    { slug: "open-source/engine", title: "Engine repository", description: "Choose a focused guide to engine repository.", source: "content/engine-source.md" },
    { slug: "open-source/engine/introduction", title: "Introduction", description: "What Rustic Engine is, implemented features, and core technologies.", source: "content/engine/introduction.md", parent: "open-source/engine" },
    { slug: "open-source/engine/getting-started", title: "Getting Started", description: "Clone, prepare, build, and run the engine from source.", source: "content/engine/getting-started.md", parent: "open-source/engine" },
    { slug: "open-source/engine/architecture", title: "Architecture", description: "Editor, runtime, rendering, physics, scripting, and asset ownership.", source: "content/engine/architecture.md", parent: "open-source/engine" },
    { slug: "open-source/engine/project-structure", title: "Project Structure", description: "Navigate the Rust workspace, applications, crates, and game project files.", source: "content/engine/project-structure.md", parent: "open-source/engine" },
    { slug: "open-source/engine/rendering-system", title: "Rendering System", description: "Graphics backends, automatic selection, diagnostics, and performance.", source: "content/engine/rendering-system.md", parent: "open-source/engine" },
    { slug: "open-source/engine/scripting-architecture", title: "Scripting Architecture", description: "Language adapters, execution, script components, lifecycle, and reload.", source: "content/engine/scripting-architecture.md", parent: "open-source/engine" },
    { slug: "open-source/engine/scene-system", title: "Scene System", description: "Scene loading, stable objects, components, versioned storage, and recovery.", source: "content/engine/scene-system.md", parent: "open-source/engine" },
    { slug: "open-source/engine/editor-development", title: "Editor Development", description: "Develop panels, project manager flows, workspaces, and debugging tools.", source: "content/engine/editor-development.md", parent: "open-source/engine" },
    { slug: "open-source/engine/building-packaging", title: "Building & Packaging", description: "Build profiles, operating-system requirements, and Windows packaging.", source: "content/engine/building-packaging.md", parent: "open-source/engine" },
    { slug: "open-source/engine/extending", title: "Extending the Engine", description: "Add functionality, modules, importers, scripting APIs, and custom tooling.", source: "content/engine/extending.md", parent: "open-source/engine" },
    { slug: "open-source/engine/troubleshooting", title: "Troubleshooting", description: "Diagnose build failures, graphics initialization, and runtime problems.", source: "content/engine/troubleshooting.md", parent: "open-source/engine" },
    { slug: "open-source/engine/contributing", title: "Contributing", description: "Engine pull requests, coding standards, validation, and bug reports.", source: "content/engine/contributing.md", parent: "open-source/engine" },
    { slug: "open-source/engine/languages-and-architecture", title: "Languages and architecture", description: "Languages and architecture for Engine repository.", source: "content/engine-source/languages-and-architecture.md", parent: "open-source/engine" },
    { slug: "open-source/engine/prerequisites", title: "Prerequisites", description: "Prerequisites for Engine repository.", source: "content/engine-source/prerequisites.md", parent: "open-source/engine" },
    { slug: "open-source/engine/fork-build-and-run-your-own-version", title: "Fork, build, and run your own version", description: "Fork, build, and run your own version for Engine repository.", source: "content/engine-source/fork-build-and-run-your-own-version.md", parent: "open-source/engine" },
    { slug: "open-source/engine/good-development-starting-points", title: "Good development starting points", description: "Good development starting points for Engine repository.", source: "content/engine-source/good-development-starting-points.md", parent: "open-source/engine" },
    { slug: "open-source/engine/main-scripts-and-commands", title: "Main scripts and commands", description: "Main scripts and commands for Engine repository.", source: "content/engine-source/main-scripts-and-commands.md", parent: "open-source/engine" },
    { slug: "open-source/engine/build-a-first-gameplay-behavior", title: "Build a first gameplay behavior", description: "Build a first gameplay behavior for Engine repository.", source: "content/engine-source/build-a-first-gameplay-behavior.md", parent: "open-source/engine" },
    { slug: "open-source/engine/diagnose-common-setup-failures", title: "Diagnose common setup failures", description: "Diagnose common setup failures for Engine repository.", source: "content/engine-source/diagnose-common-setup-failures.md", parent: "open-source/engine" },
  ] },
  { label: "Docs", docs: [
    { slug: "open-source/docs", title: "Docs repository", description: "Choose a focused guide to docs repository.", source: "content/website.md" },
    { slug: "open-source/docs/overview", title: "Documentation Overview", description: "Documentation structure, reading paths, source loading, and catalog search.", source: "content/docs/overview.md", parent: "open-source/docs" },
    { slug: "open-source/docs/local-setup", title: "Local Setup", description: "Run, build, check, and preview the documentation website locally.", source: "content/docs/local-setup.md", parent: "open-source/docs" },
    { slug: "open-source/docs/folder-structure", title: "Folder Structure", description: "Where engine guides, contributor pages, generated APIs, and site code belong.", source: "content/docs/folder-structure.md", parent: "open-source/docs" },
    { slug: "open-source/docs/writing-guidelines", title: "Writing Guidelines", description: "Supported Markdown, terminology, accuracy, and reproducible examples.", source: "content/docs/writing-guidelines.md", parent: "open-source/docs" },
    { slug: "open-source/docs/adding-documentation", title: "Adding Documentation", description: "Create pages and sections, register routes, and verify publication.", source: "content/docs/adding-documentation.md", parent: "open-source/docs" },
    { slug: "open-source/docs/editing-pages", title: "Editing Existing Pages", description: "Find authoritative sources and correct outdated information and links.", source: "content/docs/editing-pages.md", parent: "open-source/docs" },
    { slug: "open-source/docs/code-examples", title: "Code Examples", description: "Standards for scripting API samples, setup, lifecycle, and expected results.", source: "content/docs/code-examples.md", parent: "open-source/docs" },
    { slug: "open-source/docs/versioning", title: "Versioning", description: "Maintain compatibility notes and plan documentation for multiple engine versions.", source: "content/docs/versioning.md", parent: "open-source/docs" },
    { slug: "open-source/docs/translations", title: "Translations", description: "Propose languages, review translations, and understand locale support needed.", source: "content/docs/translations.md", parent: "open-source/docs" },
    { slug: "open-source/docs/contributing", title: "Contributing", description: "Submit and review documentation changes with the required website checks.", source: "content/docs/contributing.md", parent: "open-source/docs" },
    { slug: "open-source/docs/languages-and-framework", title: "Languages and framework", description: "Languages and framework for Docs repository.", source: "content/website/languages-and-framework.md", parent: "open-source/docs" },
    { slug: "open-source/docs/prerequisites", title: "Prerequisites", description: "Prerequisites for Docs repository.", source: "content/website/prerequisites.md", parent: "open-source/docs" },
    { slug: "open-source/docs/fork-and-run-your-own-version", title: "Fork and run your own version", description: "Fork and run your own version for Docs repository.", source: "content/website/fork-and-run-your-own-version.md", parent: "open-source/docs" },
    { slug: "open-source/docs/source-map-and-good-starting-points", title: "Source map and good starting points", description: "Source map and good starting points for Docs repository.", source: "content/website/source-map-and-good-starting-points.md", parent: "open-source/docs" },
    { slug: "open-source/docs/main-scripts-and-workflows", title: "Main scripts and workflows", description: "Main scripts and workflows for Docs repository.", source: "content/website/main-scripts-and-workflows.md", parent: "open-source/docs" },
    { slug: "open-source/docs/publish-your-own-documentation-site", title: "Publish your own documentation site", description: "Publish your own documentation site for Docs repository.", source: "content/website/publish-your-own-documentation-site.md", parent: "open-source/docs" },
    { slug: "open-source/docs/diagnose-common-setup-failures", title: "Diagnose common setup failures", description: "Diagnose common setup failures for Docs repository.", source: "content/website/diagnose-common-setup-failures.md", parent: "open-source/docs" },
    { slug: "open-source/docs/documentation", title: "Writing documentation", description: "Add guides, maintain API pages, and make content searchable.", source: "content/documentation.md" },
    { slug: "open-source/docs/development", title: "Development & deployment", description: "Choose a focused guide to development & deployment.", source: "README.md" },
    { slug: "open-source/docs/development/development-and-build", title: "Development and build", description: "Development and build for Development & deployment.", source: "README/development-and-build.md", parent: "open-source/docs/development" },
    { slug: "open-source/docs/development/cloudflare-pages-deployment", title: "Cloudflare Pages deployment", description: "Cloudflare Pages deployment for Development & deployment.", source: "README/cloudflare-pages-deployment.md", parent: "open-source/docs/development" },
  ] },
  { label: "Examples", docs: [
    { slug: "open-source/examples", title: "Examples repository", description: "Choose a focused guide to examples repository.", source: "content/examples.md" },
    { slug: "open-source/examples/current-contents-and-development-language", title: "Current contents and development language", description: "Current contents and development language for Examples repository.", source: "content/examples/current-contents-and-development-language.md", parent: "open-source/examples" },
    { slug: "open-source/examples/prerequisites", title: "Prerequisites", description: "Prerequisites for Examples repository.", source: "content/examples/prerequisites.md", parent: "open-source/examples" },
    { slug: "open-source/examples/start-your-own-example-project", title: "Start your own example project", description: "Start your own example project for Examples repository.", source: "content/examples/start-your-own-example-project.md", parent: "open-source/examples" },
    { slug: "open-source/examples/main-scripts-and-useful-starting-points", title: "Main scripts and useful starting points", description: "Main scripts and useful starting points for Examples repository.", source: "content/examples/main-scripts-and-useful-starting-points.md", parent: "open-source/examples" },
    { slug: "open-source/examples/license-and-common-pitfalls", title: "License and common pitfalls", description: "License and common pitfalls for Examples repository.", source: "content/examples/license-and-common-pitfalls.md", parent: "open-source/examples" },
  ] },
  { label: "Hosting SDK", docs: [
    { slug: "open-source/hosting-sdk", title: "Hosting SDK repository", description: "Choose a focused guide to hosting sdk repository.", source: "content/hosting-sdk.md" },
    { slug: "open-source/hosting-sdk/current-contents-and-development-language", title: "Current contents and development language", description: "Current contents and development language for Hosting SDK repository.", source: "content/hosting-sdk/current-contents-and-development-language.md", parent: "open-source/hosting-sdk" },
    { slug: "open-source/hosting-sdk/prerequisites", title: "Prerequisites", description: "Prerequisites for Hosting SDK repository.", source: "content/hosting-sdk/prerequisites.md", parent: "open-source/hosting-sdk" },
    { slug: "open-source/hosting-sdk/start-your-own-version", title: "Start your own version", description: "Start your own version for Hosting SDK repository.", source: "content/hosting-sdk/start-your-own-version.md", parent: "open-source/hosting-sdk" },
    { slug: "open-source/hosting-sdk/main-scripts-and-implementation-entry-points", title: "Main scripts and implementation entry points", description: "Main scripts and implementation entry points for Hosting SDK repository.", source: "content/hosting-sdk/main-scripts-and-implementation-entry-points.md", parent: "open-source/hosting-sdk" },
    { slug: "open-source/hosting-sdk/license-and-related-projects", title: "License and related projects", description: "License and related projects for Hosting SDK repository.", source: "content/hosting-sdk/license-and-related-projects.md", parent: "open-source/hosting-sdk" },
  ] },
];

const sourceGroups = ["Open-Sourced Docs", "Engine source", "Docs", "Examples", "Hosting SDK"];
export const docSections = [
  { title: "Engine", href: "/docs/engine", groups: docGroups.filter((group) => !sourceGroups.includes(group.label)) },
  { title: "Open-Sourced Docs", href: "/docs/open-source", groups: docGroups.filter((group) => sourceGroups.includes(group.label)) },
];

export const docAliases: Record<string, string> = {
  "repositories": "open-source",
  "website": "open-source/docs",
  "website/documentation": "open-source/docs/documentation",
  "website/development": "open-source/docs/development",
  "examples": "open-source/examples",
  "hosting-sdk": "open-source/hosting-sdk",
};
export function resolveDocSlug(slug: string) { return docAliases[slug] ?? slug; }
export function canonicalDocPath(pathname: string) { return routeFor(resolveDocSlug(pathname.replace(/^\/docs\/?/, ""))); }

export const allDocs = docSections.flatMap((section) => section.groups.flatMap((group) => group.docs.map((doc) => ({ ...doc, group: group.label, project: section.title }))));
export function routeFor(slug: string) { return slug ? `/docs/${slug}` : "/docs"; }

export function projectForPath(pathname: string) {
  const canonicalPath = canonicalDocPath(pathname);
  return canonicalPath === "/docs/open-source" || canonicalPath.startsWith("/docs/open-source/") ? "Open-Sourced Docs" : "Engine";
}

export function searchRouteFor(project: string) {
  return project === "Open-Sourced Docs" ? "/docs/open-source/search" : "/docs/search";
}
